sudo: required

services:
  - docker

language: go
go:
  - 1.8

env:
  global:
    - GH=mh-cbon/cct
    - JEKYLL=pietromenna/jekyll-cayman-theme
    - APP=cct
    - EMAIL=mh-cbon@users.noreply.github.com
    - MYAPP=cct
    - MYEMAIL=mh-cbon@users.noreply.github.com
    - secure: fTThhsvb3MzItw8y81Inse/NVS4KbirH92ATP1uS++Hw+NDVtm5CdsgMlovB3gDOR4CEoUnQE1auGToibD840z4HPyLrhYGTKNmoYdQVk8vrtuCwQBWBzPG1+fvym3lCsO54w7xnjfw9zbPVf6WPa1WnD0UNcllm5T0uXy0fgYStqTRlHshdRkd2ECFevLR3Q8BJHF7s7QPNJ5vw1ATfQBQM6m6xY3R+txK86B0aRn+sIOZjQgjRkp0sEhu8WfQDsUc1lZVczzQkR8kdfwo6Dte1zgBXwgTkxEYW4HiMMq+Aa6nN+625SrPHpBWXLBRP9WwnL9IECVGfQAbogC+T9aaJbBXpr1h4Gm+Vgbw8zmTLDqL6YbXGeB54E01Bw4aB0+IGa/if1nouLI6ergrWfqtD1TQr6q6u5FQWfW47KZKyiQBNE/ZKHOb1NLJBIyRocCs9lEJnfgDTY4UTkmXj3BDgB2q92z5+a56Ha27lizrUYZYsAbYig069DZKk+XFn9G/RfmG9JM98sSJ02S4P8L4Mx3AX4AY7k/MNhYH3G+PLe5LZ7sxRkqjTRl0jGqA/qWe1+kalNG66c+DFUlpOWNE+rSvjaCTV0rrPbgC7DaLb7DoHmKlYDs+Qxd3UTTOChJp7CpxqzBJctVjJKwSiCtKDdpGlITgQNkpUMinwFUc=

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin

install:
  - cd $GOPATH/src/github.com/$GH
  - go install

script:
  - echo "pass"


before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/$APP main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/$APP main.go
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh | GH=$GH sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/create-pkg.sh | GH=$GH sh -xe

after_deploy:
  - wget -O - https://raw.githubusercontent.com/mh-cbon/gh-pages/master/all.sh | sh -x
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=$GH EMAIL=$EMAIL sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/setup-repository.sh | GH=$GH EMAIL=$EMAIL sh -xe

deploy:
  provider: releases
  api_key:
    - secure: faM+7jj7uEz0rgu7XMIFuUGoVvc+rKXu3KUFdzaj2Fu1r0Ayc2sszzkWkMhH/sFfj+SHnOAy4gTxMH3h4JEaWNs2yUsCSHRbFzC2Ng2+hyizCepgtqwLCa3DGJ4EoJwaPKxhgx2pu6/uPucanxOpJqEt4J83ZacvU/ji3dQaEeKFv1WxO6Pvf9cpw43g5EjqF/utpuEqNIxPDsbHhpg2nWv/oEdVJVxkCJ3djoH2oGwbmDpRXcCB6dlwsePOKEo2Heynm9HAjQBy5YVMS4d5iwMDwXI0otlb2EfnGuoovhDa687tDjDi3U2L977WM/NeCyigNGYLaHcfUwP1UY14nARve8dTrEDt5zdze0GiYU60EZCoeLgma57+vVEkx7XJCbQQ/BmT7n1EtrXd0oBuBeXayLe1wtgZs1gffdc+cWX7HFsfqJXoWKlXGi1A97IGIA4WYznuxlYNHoy9InQCBWbVQF5KL+sNFuP/yEx0jXd/AmGDxfFdpzYmjR9azJA/iA3RvJEk/gCaXBaiKNxFIXPTM1S1afa2fC6/WVfDOO4dYfXEFqKRKm+13b2+D/AGeQLcJ4rZD74nO7ywFWhK/MifBHPWqvRHN05m988DJNDUP7UyDwPwnIaxHp9AeZtlxizr7Yn8LlWL9MySy14tJYuboYJ/1EbiOJLWNas9Bz8=
  file_glob: true
  file:
    - $APP-386.deb
    - $APP-amd64.deb
    - $APP-386.rpm
    - $APP-amd64.rpm
  skip_cleanup: true
  on:
    tags: true
